### PR TITLE
Fade ins and outs, load runepage button

### PR DESCRIPTION
**Pull request by robinwithes**
https://gyazo.com/0abc98d864b4eaf07b2ee42cd4a31cc5

### CODE REVIEW

**Comment by robinwithes** [comment]
Added load button back

**Comment by robinwithes** [comment]
@stirante I'll change the title when i'm done with everything but feel free to approve or deny changes already.

**Comment by robinwithes** [comment]
Chaned the load button to be able to overwrite client rune pages integrating the second list stirante added.
Only thing left now is organising the runebutton a little bit.

**Comment by robinwithes** [comment]
Done with this pr, i could'n figure out how to make the runebutton more organised.

**Review by stirante — APPROVED** [review]

**Pull request merged**
